# NumPy Arrays

In [1]:
x = [1,2,3,4]

In [2]:
type(x)

list

In [3]:
import numpy as np

In [8]:
n_x = np.array(x)

In [9]:
n_x

array([1, 2, 3, 4])

In [10]:
type(n_x)

numpy.ndarray

In [12]:
d_2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [13]:
np.array(d_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# Gives evenly seperated 3rd argument no. of points
np.linspace(0, 20, 7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [23]:
# Identity matrics
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(10)

array([0.72598087, 0.46232702, 0.40671638, 0.64235438, 0.49671894,
       0.5042266 , 0.997591  , 0.41957102, 0.90486112, 0.12592469])

In [25]:
np.random.rand(5,5)

array([[0.36561453, 0.25846593, 0.55843453, 0.15223639, 0.5141183 ],
       [0.45524581, 0.29184846, 0.88178311, 0.66096118, 0.78537717],
       [0.59580816, 0.64704572, 0.34513785, 0.60250338, 0.98369563],
       [0.68395944, 0.83842842, 0.2247669 , 0.53519598, 0.89342364],
       [0.48458696, 0.86097899, 0.56141475, 0.43019183, 0.3059534 ]])

In [26]:
np.random.randn(2)

array([-2.2892057 , -0.19715116])

In [27]:
np.random.randint(0, 50)

12

In [28]:
np.random.randint(0, 50, 10)

array([18, 25, 19, 49, 41, 42, 32,  8,  3, 10], dtype=int32)

In [34]:
#  reshape
arr = np.arange(1, 26)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [35]:
arr.reshape(5, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
arr.max()

np.int64(25)

In [38]:
arr.min()

np.int64(1)

In [39]:
arr.argmax()

np.int64(24)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

arr.shape

(5, 5)

In [43]:
arr.dtype

dtype('int64')