# NumPy Indexing ans Selection

In [1]:
import numpy as np

In [4]:
arr = np.arange(0, 11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[3]

np.int64(3)

In [7]:
arr[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [8]:
arr[1:10:4]

array([1, 5, 9])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[-1]

np.int64(10)

In [12]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [13]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[:6:-1]

array([10,  9,  8,  7])

In [16]:
arr[0] = 10

In [17]:
arr

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice = arr[:5] # reference not copy

In [24]:
slice

array([  10, 1009,    2,    3,    4])

In [25]:
slice[1] = 1009

In [26]:
arr

array([  10, 1009,    2,    3,    4,    5,    6,    7,    8,    9,   10])

In [36]:
slice_copy = arr[5:].copy()

In [37]:
slice_copy[1] = 999999

In [38]:
arr

array([  10, 1009,    2,    3,    4,    5,    6,    7,    8,    9,   10])

### 2D array slicing

In [39]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [42]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr_2d[0][2]

np.int64(3)

In [44]:
arr_2d[0,2]

np.int64(3)

In [45]:
arr_2d[:][0]

array([1, 2, 3])

In [60]:
arr_2d[:2][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr_2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [51]:
arr_2d[:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr_2d[0, :]

array([1, 2, 3])

In [61]:
arr = np.arange(1,11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr_bool = arr > 5

In [64]:
arr_bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
arr[arr_bool]

array([ 6,  7,  8,  9, 10])

In [66]:
arr[arr<4]

array([1, 2, 3])

In [67]:
arr = np.arange(50).reshape(5, 10)

In [68]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
# Get 23 to 36 box
arr[2:4,3:7]

array([[23, 24, 25, 26],
       [33, 34, 35, 36]])

In [ ]:
s