# NumPy Operations


In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)

In [3]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [5]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
arr / (arr+3)

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667, 0.7       , 0.72727273, 0.75      , 0.76923077])

In [7]:
np.sqrt(40)

np.float64(6.324555320336759)

In [8]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [9]:
np.log(100)

np.float64(4.605170185988092)

In [10]:
np.exp(2)

np.float64(7.38905609893065)

In [11]:
np.sin(20)

np.float64(0.9129452507276277)