## Ex - 1 : Python program to a Sort Matrix by index-value equality count

Given a Matrix, the task is to write a Python program that can sort its rows or columns on a measure of the number of values equal to its index number. For each row or column, count occurrences of equality of index number with value. After computation of this count for each row or column, sort the matrix on basis of the count extracted for each row or column in step 1.

In [30]:
list = [[3, 1, 2, 5, 4], [0, 1, 2, 3, 4], [6, 5, 4, 3, 2], [0, 5, 4, 2]] 

In [31]:
def get_match_count(row):
    count = 0
    for i, j in enumerate(row):
        if i == j:
            count += 1
    return count

In [32]:
def sort_by_count(list):
    rows_with_count = []
    
    for row in list:
        count = get_match_count(row)
        rows_with_count.append((count, row))

    rows_with_count.sort(key=lambda x: x[0])

    matrix = [row for count, row in rows_with_count]
    return matrix

In [33]:
sort_by_count(list)

[[6, 5, 4, 3, 2], [0, 5, 4, 2], [3, 1, 2, 5, 4], [0, 1, 2, 3, 4]]

## Ex - 2: Python Program to Reverse Every Kth row in a Matrix

In [35]:
a = [[5, 3, 2], [8, 6, 3], [3, 5, 2], [3, 6], [3, 7, 4], [2, 9]]
k = 2

for idx, row in enumerate(a, start=1):
    if idx % k == 0:
        row.reverse()

In [36]:
a

[[5, 3, 2], [3, 6, 8], [3, 5, 2], [6, 3], [3, 7, 4], [9, 2]]

## Ex - 3: Python Program to Convert String Matrix Representation to Matrix

In [84]:
s = "[gfg,is],[best,for],[all,geeks]"

In [85]:
is_open = False
is_comma = False
final_list = []
lst = []
value = ""


In [86]:
for chr in s:
    if chr == "[":
        is_open = True
    elif chr == "]":
        is_open = False
        lst.append(value)
        final_list.append(lst)
        print(final_list)
        lst = []
        value = ""
    elif chr == "," and value:
        lst.append(value)
        value = ""
    elif chr.isalpha():
        value += chr

[['gfg', 'is']]
[['gfg', 'is'], ['best', 'for']]
[['gfg', 'is'], ['best', 'for'], ['all', 'geeks']]


In [88]:
final_list

[['gfg', 'is'], ['best', 'for'], ['all', 'geeks']]

In [75]:
lst =[]

for i in s[1:-1].split("],["):
    lst.append(i.split(","))

In [89]:
final_list

[['gfg', 'is'], ['best', 'for'], ['all', 'geeks']]

In [90]:
final_list.clear()

In [91]:
final_list

[]

# Ex - 4: Count the frequency of matrix row length

In [1]:
l = [[6, 3, 1], [8, 9], [2], [10, 12, 7], [4, 11]]

In [2]:
d = {}

for idx, row in enumerate(l):
    d[idx] = len(row)

In [3]:
d

{0: 3, 1: 2, 2: 1, 3: 3, 4: 2}

# Ex - 5: Convert Integer Matrix to String Matrix

In [9]:

l = [[4, 5, 7], [10, 8, 3], [19, 4, 6]]

In [10]:
for idx, row in enumerate(l):
    l[idx] = [str(val) for val in row]

In [11]:
l

[['4', '5', '7'], ['10', '8', '3'], ['19', '4', '6']]

# Ex - 6: Python Program to Convert Tuple Matrix to Tuple List

In [12]:
l = [[(4, 5), (7, 8)], [(10, 13), (18, 17)]] 
# Output : [(4, 7, 10, 18), (5, 8, 13, 17)]

In [16]:
res = []
for a,b in l:
    res.append(a+b)

In [17]:
res

[(4, 5, 7, 8), (10, 13, 18, 17)]

# Ex - 7: Group Elements in Matrix

In [39]:
l = [[5, 8], [2, 0], [5, 4], [2, 3], [2, 9]] 
# Output : {5: [8, 4], 2: [0, 3, 9]} 

In [40]:
d = {}

for row in l:
    d.setdefault(row[0], []).extend(row[1:])
        

In [41]:
d

{5: [8, 4], 2: [0, 3, 9]}

# Ex - 8: Assigning Subsequent Rows to Matrix first row elements

In [42]:
l = [[5, 8, 10], [2, 0, 9], [5, 4, 2], [2, 3, 9]] 
# Output : {5: [2, 0, 9], 8: [5, 4, 2], 10: [2, 3, 9]} 

In [44]:
d = {}

for i in range(len(l[0])):
    d.setdefault(l[0][i], []).extend(l[i+1])

In [45]:
d

{5: [2, 0, 9], 8: [5, 4, 2], 10: [2, 3, 9]}

# Ex - 9: Adding and Subtracting Matrices in Python

In [47]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.array([[4, 5], [6, 7]])


In [48]:
print(np.add(A,B))


[[ 5  7]
 [ 9 11]]


In [49]:
print(np.subtract(A,B))

[[-3 -3]
 [-3 -3]]


# Ex - 10: Convert Matrix to Dictionary

In [70]:
l = [[5, 6, 7], [8, 3, 2], [8, 2, 1]]

In [71]:
# Wrong
d = {d.setdefault(idx, []).extend(row) for idx, row in enumerate(l)} 

In [72]:
d = {idx: row for idx, row in enumerate(l)}

In [73]:
d

{0: [5, 6, 7], 1: [8, 3, 2], 2: [8, 2, 1]}

# Ex - 11: Convert Matrix to Custom Tuple Matrix

In [77]:
l = [[4, 5, 6], [6, 7, 3], [1, 3, 4]]
add_list = ['Gfg','is', 'best']
# Output : [('Gfg', 4),
 # ('Gfg', 5),
 # ('Gfg', 6),
 # ('is', 6),
 # ('is', 7),
 # ('is', 3),
 # ('best', 1),
 # ('best', 3),
 # ('best', 4)]

In [79]:
lst = []
for str, row in zip(add_list, l):
    for val in row:
        lst.append((str, val))
    

In [80]:
lst

[('Gfg', 4),
 ('Gfg', 5),
 ('Gfg', 6),
 ('is', 6),
 ('is', 7),
 ('is', 3),
 ('best', 1),
 ('best', 3),
 ('best', 4)]

# Ex - 12: Matrix Row subset

In [81]:
l = [[4, 5, 7], [2, 3, 4], [9, 8, 6]]
check = [[2, 3], [1, 2], [9, 0]]

In [86]:
subset = []

for row in check:
    for l_row in l:
        if all(elem in l_row for elem in row):
            subset.append(row)
            break

In [87]:
subset

[[2, 3]]

# Ex - 13: Group similar elements into Matrix

In [88]:
l = [1, 3, 4, 4, 2, 3, 4]
# Output : [[1], [2], [3, 3], [4, 4]

In [89]:
l.sort()

In [90]:
l

[1, 2, 3, 3, 4, 4, 4]

In [93]:
from collections import defaultdict

grouped_data = defaultdict(list)

for item in l:
    grouped_data[item].append(item)

In [95]:
result_list = list(grouped_data.values())

In [96]:
result_list

[[1], [2], [3, 3], [4, 4, 4]]

# Ex - 14: Row-wise element Addition in Tuple Matrix

In [98]:
l = [('Gfg', 3), ('best', 1)] 
add = [1, 2]

In [100]:
res = []

for idx, tup in enumerate(l):
    lst = list(tup)
    lst.append(add[idx])
    res.append(tuple(lst))

In [101]:
res

[('Gfg', 3, 1), ('best', 1, 2)]

# Ex - 15: Create an n x n square matrix, where all the sub-matrix have the sum of opposite corner elements as even

In [126]:
count = 1
n = 4
matrix = np.zeros((n, n))

In [127]:
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
for i in range(n):
    for j in range(n):
        matrix[i][j] = int(count)
        count += 1
    count -= 1

In [135]:
matrix

array([[13., 14., 15., 16.],
       [16., 17., 18., 19.],
       [19., 20., 21., 22.],
       [22., 23., 24., 25.]])

In [130]:
type(matrix[0][0])

numpy.float64